config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("complexes/", include("complexes.urls", namespace="complexes")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("questions/", include("questions.urls", namespace="questions")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("users/", include("users.urls", namespace="users")),
    path("manage/", include("managements.urls", namespace="managements")),
    path("", include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

sales/urls.py
from django.urls import path
from . import views

app_name = "sales"

urlpatterns = [
    path("list/", views.SaleHomeView.as_view(), name="list"),
    path("create/", views.SaleCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", views.SaleDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.SaleUpdateView.as_view(), name="update"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view, name="logout"),
]

templates/partials/navbar.html
{% load static %}
<nav class="navbar">
    <div class="nav-logo">
        <a href="{% url 'core:home' %}">
            <img src="{% static 'photos/logo.jpg' %}" alt="로고">
        </a>
    </div>
    <div>
        <div class="navbar-link">
            <a href="{% url 'sales:list' %}">
                <span>
                    매물검색
                </span>
            </a>
            <a href="">
                <span>
                    실거래가조회
                </span>
            </a>
            <a href="">
                <span>
                    부동산소개
                </span>
            </a>
        </div>
    </div>
    <div class="navbar-login">
        {% if user.is_authenticated %}
        <div class="navbar-login__box">
            <a href="{% url 'managements:home' %}"><span>관리자 페이지</span></a>
        </div>
        <div class="navbar-login__box">
            <a href="{% url 'users:logout' %}"><span>로그아웃</span></a>
        </div>
        {% else %}
        <div class="navbar-login__box">
            <a href="{% url 'users:login' %}"><span>로그인</span></a>
        </div>
        {% endif %}
    </div>
</nav>

templates/partials/paginator.html
<!-- Paginator -->
<div>
    <ul>
        <!-- 이전 페이지 -->
        {% if page_obj.has_previous %}
        <li>
            <a href="?page={{ page_obj.previous_page_number}}">Previous</a>
        </li>
        {% else %}
        <li>
            <a>Previous</a>
        </li>
        {% endif %}


        <!-- 페이지 링크들 -->
        {% for n in page_obj.paginator.page_range %}
        {% if page_obj.number == n %}
        <li>
            <span>{{ n }}</span>
        </li>
        {% elif n > page_obj.number|add:'-5' and n < page_obj.number|add:'5' %} <li>
            <a href="?page={{ n }}">{{ n }}</a>
            </li>
            {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{page_obj.next_page_number}}">Next</a>
            </li>
            {% else %}
            <li>
                <a>Next</a>
            </li>
            {% endif %}
    </ul>
</div>

templates/partials/sidebar.html
<div id="sidebar-form">
    <form action="{% url 'questions:create' %}?next={{request.path}}" method="POST" class="sidebar-form">
        <h4>상담 문의</h4>
        {% csrf_token %}
        <input type="text" placeholder="이름을 입력해주세요" name="name" required>
        <input type="text" placeholder="전화번호를 입력해주세요" name="phone" onkeypress='return inputOnlyNumber(event)' required>
        <textarea placeholder="문의하실 내용을 입력해주세요" name="text" required></textarea>
        <div id="sidebar-form__check" class="sidebar-form__check">
            <div>
                <input type="checkbox" id="sidebar-form__check-input" class="sidebar-form__check-input" required>
                <label for="sidebar-form__check-input">
                    개인정보 수집/이용 동의(필수)
                </label>
            </div>
            <button id="sidebar-form__check-toggle">
                보기
            </button>
        </div>
        <div class="sidebar-form__check-toggle-text display-none">
            <table>
                <tbody>
                    <tr>
                        <th>항목</th>
                        <td>이름, 연락처, 문의내용</td>
                    </tr>
                    <tr>
                        <th>수집/이용<br>목적</th>
                        <td>매물문의상담 서비스 이용</td>
                    </tr>
                    <tr>
                        <th>보유/이용<br>기간</th>
                        <td>상담완료 1개월 후 파기</td>
                    </tr>
                </tbody>
            </table>
            <span>*귀하는 개인정보 수집에 동의에 거부할 권리가 있으며, 동의를 거부할 경우 상담을 받으실 수 없습니다.</span>
        </div>
        <input type="submit" value="문의하기" class="sidebar-form__submit">
    </form>
</div>