config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("complexes/", include("complexes.urls", namespace="complexes")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("questions/", include("questions.urls", namespace="questions")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("users/", include("users.urls", namespace="users")),
    path("manage/", include("managements.urls", namespace="managements")),
    path("", include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

sales/urls.py
from django.urls import path
from . import views

app_name = "sales"

urlpatterns = [
    path("list/", views.SaleHomeView.as_view(), name="list"),
    path("create/", views.SaleCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", views.SaleDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.SaleUpdateView.as_view(), name="update"),
]

sales/models.py
import random

from django.db import models
from core.models import TimeStampedModel
from django.core.validators import MinValueValidator


class Sale(TimeStampedModel):

    """Sale Model"""

    TYPE_SALE = "sale"
    TYPE_JEONSE = "jeonse"
    TYPE_MONTHLY = "monthly"
    TYPE_CHOICES = (
        (TYPE_SALE, "Sale"),
        (TYPE_JEONSE, "Jeonse"),
        (TYPE_MONTHLY, "Monthly"),
    )

    complex_sub = models.ForeignKey(
        "complexes.ComplexSub",
        related_name="sale",
        on_delete=models.SET_NULL,
        null=True,
    )
    address = models.TextField(blank=True, null=True)
    type = models.CharField(choices=TYPE_CHOICES, max_length=7)
    deposit = models.IntegerField(
        null=True, blank=True, validators=[MinValueValidator(0)]
    )
    amount = models.IntegerField(validators=[MinValueValidator(0)])
    floor = models.IntegerField()
    loan = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    administrative_expense = models.IntegerField(validators=[MinValueValidator(0)])
    available_date = models.DateField()
    description = models.TextField()
    one_description = models.TextField()
    is_sold = models.BooleanField()

    def first_image(self):
        images = self.sale_image.all()
        return images[0]


def sale_directory_path(instance, filename):
    n = random.randint(10000, 99999)
    return f"sale/sale_{instance.id}/{filename}-{n}"


class SaleImage(TimeStampedModel):

    """Sale Image Model"""

    sale = models.ForeignKey(Sale, related_name="sale_image", on_delete=models.CASCADE)
    image = models.ImageField(upload_to=sale_directory_path)
    description = models.TextField()

sales/forms.py
from django import forms
import datetime

from . import models
from complexes import models as complexes_models


class SearchForm(forms.Form):

    TYPE_SALE = "sale"
    TYPE_JEONSE = "jeonse"
    TYPE_MONTHLY = "monthly"
    TYPE_CHOICES = (
        (TYPE_SALE, "매매"),
        (TYPE_JEONSE, "전세"),
        (TYPE_MONTHLY, "월세"),
    )

    sale_type = forms.MultipleChoiceField(
        choices=TYPE_CHOICES,
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "search-type-btn", "checked": ""}
        ),
        label="",
        required=True,
    )

    price_from = forms.IntegerField(label="", initial=0, min_value=0, required=False)
    price_to = forms.IntegerField(
        label="", initial=1000000000, min_value=0, required=False
    )
    date_from = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), label="", required=False
    )
    date_to = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), label="", required=False
    )


class SearchApartmentForm(forms.Form):
    apartments = forms.ModelMultipleChoiceField(
        queryset=complexes_models.Complex.objects.all()
    )


class SearchNotApartmentForm(forms.Form):

    ADDRESS_EOMSA = "엄사"
    ADDRESS_GEUMAM = "금암"
    ADDRESS_DUMA = "두마"
    ADDRESS_DAESIL = "대실"
    ADDRESS_CHOICES = (
        (ADDRESS_DAESIL, "대실지구"),
        (ADDRESS_GEUMAM, "금암동"),
        (ADDRESS_DUMA, "두마면"),
        (ADDRESS_EOMSA, "엄사면"),
    )
    address = forms.MultipleChoiceField(
        choices=ADDRESS_CHOICES,
        widget=forms.CheckboxSelectMultiple(
            attrs={"class": "search-address-btn", "checked": ""}
        ),
        label="",
        required=True,
    )


class SaleForm(forms.ModelForm):
    class Meta:
        model = models.Sale
        fields = (
            "type",
            "address",
            "deposit",
            "amount",
            "floor",
            "loan",
            "administrative_expense",
            "available_date",
            "description",
            "one_description",
            "is_sold",
        )
        widgets = {
            "deposit": forms.NumberInput(attrs={"min": 0}),
            "amount": forms.NumberInput(attrs={"min": 0}),
            "loan": forms.NumberInput(attrs={"min": 0}),
            "administrative_expense": forms.NumberInput(attrs={"min": 0}),
            "available_date": forms.DateInput(attrs={"type": "date"}),
        }

    def __init__(self, *args, **kwargs):
        super(SaleForm, self).__init__(*args, **kwargs)
        self.fields["category"] = forms.ModelChoiceField(
            queryset=complexes_models.Category.objects.all()
        )
        self.fields["complex"] = forms.ModelChoiceField(
            queryset=complexes_models.Complex.objects.all()
        )
        self.fields["complex_sub"] = forms.ModelChoiceField(
            queryset=complexes_models.ComplexSub.objects.all()
        )

    def save(self, *args, **kwargs):
        sale = super().save(commit=False)
        complex_sub = self.cleaned_data.get("complex_sub")
        sale.complex_sub = complex_sub
        sale.save()

sales/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, DetailView, UpdateView, CreateView
from django.core.paginator import Paginator
from django.urls import resolve, reverse, reverse_lazy
from django.db.models import Q

from . import models
from . import forms

from complexes import models as complexes_models


class SaleHomeView(View):
    def get(self, request):
        current_url = resolve(request.path_info)
        if current_url.app_names[0] == "managements":
            template_name = "manage/sale_list.html"
        else:
            template_name = "sales/sale_list.html"
        sale_type = request.GET.get("sale_type")
        if sale_type:
            form = forms.SearchForm(request.GET or None)
            if form.is_valid():
                sale_type = form.cleaned_data.get("sale_type")
                address = form.cleaned_data.get("address")
                price_from = form.cleaned_data.get("price_from")
                price_to = form.cleaned_data.get("price_to")
                date_from = form.cleaned_data.get("date_from")
                date_to = form.cleaned_data.get("date_to")
                filter_args = {}
                if sale_type:
                    filter_args["type__in"] = sale_type
                q = None
                if address:
                    q = Q()
                    for a in address:
                        q.add(Q(address__contains=a), q.OR)
                        q.add(
                            Q(complex_sub__complex_area__complex__address__contains=a),
                            q.OR,
                        )
                if price_from is not None:
                    filter_args["amount__gte"] = price_from
                if price_to is not None:
                    filter_args["amount__lte"] = price_to
                if date_from is not None:
                    filter_args["available_date__gte"] = date_from
                if date_to is not None:
                    filter_args["available_date__lte"] = date_to
                if current_url.app_names[0] == "sales":
                    filter_args["is_sold"] = False
                qs = models.Sale.objects.filter(**filter_args)
                if q is not None:
                    qs = qs.filter(q).order_by("-pk")
                paginator = Paginator(qs, 10, orphans=4)
                page = request.GET.get("page", 1)
                sales = paginator.get_page(page)

                return render(
                    request,
                    template_name,
                    {"form": form, "sales": sales},
                )
        else:
            form = forms.SearchForm(prefix="basic")
            apartment_form = forms.SearchApartmentForm(prefix="apartment")
            not_apartment_form = forms.SearchNotApartmentForm(prefix="not_apartment")
            if current_url.app_names[0] == "sales":
                sales_list = models.Sale.objects.filter(is_sold=False).order_by("-pk")
            else:
                sales_list = models.Sale.objects.order_by("-pk")
            paginator = Paginator(sales_list, 10, orphans=4)
            page = request.GET.get("page", 1)
            sales = paginator.get_page(page)
        return render(
            request,
            template_name,
            {
                "form": form,
                "apartment_form": apartment_form,
                "not_apartment_form": not_apartment_form,
                "sales": sales,
            },
        )


class SaleDetailView(DetailView):

    model = models.Sale
    content_object_name = "sale"


class SaleUpdateView(UpdateView):

    model = models.Sale
    form_class = forms.SaleForm

    def get_context_data(self, *args, **kwargs):
        context = super(SaleUpdateView, self).get_context_data(*args, **kwargs)
        context["page_title"] = "매물 수정"
        return context

    def get_success_url(self):
        return reverse_lazy("sales:detail", kwargs={"pk": self.object.pk})


class SaleCreateView(CreateView):

    model = models.Sale
    form_class = forms.SaleForm

    def get_context_data(self, *args, **kwargs):
        context = super(SaleCreateView, self).get_context_data(*args, **kwargs)
        context["page_title"] = "매물 생성"
        context["complex_sub_list"] = complexes_models.ComplexSub.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy("sales:list")

templates/sales/sale_detail.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
매물 상세
{% endblock page_title %}

{% block content %}
<h3>매물 상세</h3>
{% if user.is_authenticated %}
<a href="{% url 'sales:update' pk=sale.pk %}">수정</a>
<a href="">삭제</a>
{% endif %}
<table border="1">
    <tr>
        <th>건물</th>
        <td>{{sale.complex_sub}}</td>
    </tr>
    <tr>
        <th>주소</th>
        <td>{{sale.address}}</td>
    </tr>
    <tr>
        <th>타입</th>
        <td>{{sale.type}}</td>
    </tr>
    {% if sale.type == "monthly" %}
    <tr>
        <th>보증금</th>
        <td>{{sale.deposit}}</td>
    </tr>
    {% endif %}
    <tr>
        <th>가격</th>
        <td>{{sale.amount}}</td>
    </tr>
    <tr>
        <th>층</th>
        <td>{{sale.floor}}</td>
    </tr>
    <tr>
        <th>융자</th>
        <td>{{sale.loan}}</td>
    </tr>
    <tr>
        <th>관리비</th>
        <td>{{sale.administrative_expense}}</td>
    </tr>
    <tr>
        <th>입주 가능일</th>
        <td>{{sale.available_date}}</td>
    </tr>
    <tr>
        <th>설명</th>
        <td>{{sale.description}}</td>
    </tr>
    <tr>
        <th>판매완료 여부</th>
        <td>{{sale.is_sold}}</td>
    </tr>
</table>
{% for image in sale.sale_image.all %}
<img src="{% static image.image %}" width="100px">
{% endfor %}
{% endblock %}

templates/sales/sale_form.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
{{page_title}}
{% endblock page_title %}
{% block content %}
<h2>{{page_title}}</h2>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="제출">
</form>
{% endblock %}

templates/sales/sale_list.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
매물목록
{% endblock page_title %}

{% block content %}
<div class="toggle">
    <div class="toggle-box toggle__now" id="toggle-0">
        <i class="fa-solid fa-building fa-2xl"></i>
        <span>아파트</span>
    </div>
    <div class="toggle-box" id="toggle-1">
        <i class="fa-solid fa-house-laptop fa-2xl"></i>
        <span>기타</span>
    </div>
</div>

<div style="border:1px solid black">
    <h4>검색</h4>
    <form action="{{url}}" method="GET" id="search-form">
        <div>
            분류<br>
            <span id="type_all" class="search_all_checked">전체</span>
            {{form.sale_type}}
        </div>
        <div id="list-0" class="toggle-show">
            {% include 'sales/search_apartment_form.html' %}
        </div>
        <div id="list-1" class="toggle-noshow">
            {% include 'sales/search_not_apartment_form.html' %}
        </div>
        <div>
            가격
            {{form.price_from}} ~ {{form.price_to}}
        </div>
        <div>
            입주가능일
            {{form.date_from}} ~ {{form.date_to}}
        </div>
        <div>
            <input type="reset" value="초기화">
            <input type="submit" value="검색">
        </div>
    </form>
</div>
<table>
    <thead>
        <tr>
            <th>
                번호
            </th>
            <th>
                분류
            </th>
            <th>
                단지
            </th>
            <th>
                가격
            </th>
            <th>
                상세보기
            </th>
        </tr>
    </thead>
    <tbody>
        {% for sale in sales %}
        <tr>
            <td>
                {{sale.pk}}
            </td>
            <td>{% if sale.type == 'sale' %}
                매매
                {% elif sale.type == 'jeonse' %}
                전세
                {% else %}
                월세
                {% endif %}
            </td>
            <td>
                {{sale.complex_sub}}
            </td>
            <td>
                {{sale.amount}}
            </td>
            <td>
                <a href="{% url 'sales:detail' pk=sale.pk %}">상세보기</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% include 'partials/paginator.html' with page_obj=sales %}

{% endblock %}

templates/sales/search_apartment_form.html
<div>
    아파트<br>
    <span id="apartment_all" class="search_all_checked">전체</span>
    {{apartment_form.apartments}}
</div>

templates/sales/search_form.html
<form method="GET" action="" id="search_sale_form">
    {% csrf_token %}
    <div>
        분류<br>
        <span id="type_all" class="search_all_checked">전체</span>
        {{form.sale_type}}
    </div>
    <div>
        위치<br>
        <span id="address_all" class="search_all_checked">전체</span>
        {{form.address}}
    </div>
    <div>
        가격
        {{form.price_from}} ~ {{form.price_to}}
    </div>
    <div>
        입주가능일
        {{form.date_from}} ~ {{form.date_to}}
    </div>
    <input type="reset" value="초기화">
    <input type="submit" value="검색">
</form>

templates/sales/search_not_apartment_form.html
<div>
    주소<br>
    <span id="address_all" class="search_all_checked">전체</span>
    {{not_apartment_form.address}}
</div>