config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("complexes/", include("complexes.urls", namespace="complexes")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("questions/", include("questions.urls", namespace="questions")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("users/", include("users.urls", namespace="users")),
    path("manage/", include("managements.urls", namespace="managements")),
    path("", include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

questions/urls.py
from django.urls import path
from . import views

app_name = "questions"

urlpatterns = [
    path("list/", views.QuestionListView.as_view(), name="list"),
    path("create/", views.question_create_view, name="create"),
    path("<int:pk>/detail/", views.QuestionDetailView.as_view(), name="detail"),
]

questions/models.py
from django.db import models
from core.models import TimeStampedModel
import random


class Question(TimeStampedModel):

    """Question Model"""

    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=20)
    text = models.TextField()
    is_answered = models.BooleanField(default=False)

questions/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView, CreateView
from django.http import HttpResponseRedirect

from . import models

# Create your views here.
class QuestionListView(ListView):

    model = models.Question
    paginate_by = 10
    paginate_orphans = 4
    context_object_name = "questions"
    ordering = "-pk"


class QuestionDetailView(DetailView):

    model = models.Question


def question_create_view(request):
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        text = request.POST.get("text")
        question = models.Question.objects.create(name=name, phone=phone, text=text)
        question.save()
        return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))

templates/questions/question_detail.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
문의글 상세보기
{% endblock page_title %}


{% block content %}
<h2>문의글 보기</h2>
<table>
    <tr>
        <th>제목</th>
        <td>{{question.title}}</td>
    </tr>
    <tr>
        <th>전화번호</th>
        <td>{{question.phone}}</td>
    </tr>
    <tr>
        <th>비밀글 여부</th>
        <td>{{question.secret}}</td>
    </tr>
    <tr>
        <th>내용</th>
        <td>{{question.text}}</td>
    </tr>
    <tr>
        <th>답변 여부</th>
        <td>{{question.is_answered}}</td>
    </tr>
</table>
{% if user.is_authenticated %}
<a href="">문의 확인 처리</a>
{% endif %}

{% endblock %}

templates/questions/question_list.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}
문의글 목록
{% endblock page_title %}

{% block content %}
<br><br>
<a href="{% url 'questions:create' %}">문의하기</a>
<h2>문의리스트</h2>
{% for question in questions %}
<a href="{% url 'questions:detail' pk=question.pk %}">{{question.name}}</a><br>
{% endfor %}
{% include 'partials/paginator.html' %}
{% endblock %}