config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("complexes/", include("complexes.urls", namespace="complexes")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("questions/", include("questions.urls", namespace="questions")),
    path("sales/", include("sales.urls", namespace="sales")),
    path("users/", include("users.urls", namespace="users")),
    path("manage/", include("managements.urls", namespace="managements")),
    path("", include("core.urls", namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

sales/urls.py
from django.urls import path
from . import views

app_name = "sales"

urlpatterns = [
    path("list/", views.SaleHomeView.as_view(), name="list"),
    path("create/", views.SaleCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", views.SaleDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.SaleUpdateView.as_view(), name="update"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}{% endblock page_title %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>
    <header class="header">
        {% include 'partials/navbar.html' %}
    </header>
    <main>
        <div id="sidebar">
            {% include 'partials/sidebar.html' %}
        </div>
        <div class="main" id="main">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>

    </footer>
    <script src="{% static 'javascript/clickCheckInput.js' %}"></script>
    <script src="{% static 'javascript/changeFromToInput.js' %}"></script>
    <script src="{% static 'javascript/toggleBox.js' %}"></script>
    <script src="{% static 'javascript/before_submit.js' %}"></script>
    <script src="https://kit.fontawesome.com/38082222d0.js" crossorigin="anonymous"></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
XX부동산
{% endblock page_title %}


{% block content %}
<div class="home-title">
    <h2>최신 매물</h2>
    <a href="{% url 'sales:list' %}">최신 매물 더보기 <i class="fa-solid fa-arrow-right-long"></i></a>
</div>
<div class="sale-container">
    {% for sale in sales %}
    <a class="sale-card" href="{% url 'sales:detail' pk=sale.pk %}">
        <img src="{% get_static_prefix%}{{sale.first_image.image}}" alt="{{sale.pk}}이미지" class="sale-card__img">
        <span class="sale-card__address">
            {{sale.complex_sub.complex_area.complex.name}} {{sale.complex_sub.building}}동
        </span>
        <div class="sale-card__money">
            <div class="sale-card__type">
                {% if sale.type == 'monthly' %}
                <span class="sale-card__type-monthly">
                    월세
                </span>
                {% elif sale.type == 'jeonse' %}
                <span class="sale-card__type-jeonse">
                    전세
                </span>
                {% else %}
                <span class="sale-card__type-sale">
                    매매
                </span>
                {% endif %}
            </div>
            <span class="sale-card__amount">
                {% if sale.type == 'monthly' %}
                {{sale.deposit}} /
                {% endif %}
                {{sale.amount}}
            </span>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}